export default function HomePage() {
    return (
        <main className="p-4">
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
            <p>Home page</p>
        </main>
    );
}
